sudo: false
language: python
python: "3.8"
addons:
  firefox: "60.0.2"
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "npm install -g selenium-standalone@6.15.2"
  - "selenium-standalone install"
  - "selenium-standalone start &"
dist: xenial
matrix:
  include:
    - python: 3.8
      env: TESTENV=linters
    - python: 3.8
      env: TESTENV=coveralls
    - python: 3.8
      env: TESTENV=py38-pytest-latest
    - python: 3.8
      env: TESTENV=py38
install:
  - pip install tox
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
